### ISSUE TITLE
Two Improvements to Control.Monad.Free.Church

### ISSUE THREAD

**Issue by Zemyla** [ekmett/free#100]
I was looking at Control.Monad.Free.Church, and I thought of two ways it could be improved.

1) Add an explicit definition for foldMap of (F f): foldMap f x = runF x f fold

2) Change the definition of cutoff:
cutoff n _ | n <= 0 = return Nothing
cutoff n (F m) = F $ \kp kf -> m (\a n -> kp (if n <= 0 then Nothing else Just a)) (\f n -> if n <= 0 then kp Nothing else let n' = n - 1 in n' `seq` kf (fmap ($ n') f)) n

I would submit these improvements, but my computer just died.

**Comment by RyanGlScott** [comment]
Fixed in #134.
