### ISSUE TITLE
Faster Free Applicatives

### ISSUE THREAD

**Issue by Zemyla** [ekmett/free#115]
Dave Menendez has written [two](http://www.eyrie.org/~zednenem/2013/05/27/freeapp) [articles](http://www.eyrie.org/~zednenem/2013/06/freeapp-2) on how to make faster free applicatives with Church encoding. He has benchmarks showing his final solution, B2, is much faster (O(n) instead of O(n²)). It can also become a free Alternative by changing z in the solution to (z -> z), the same way the CPS list monad works.

**Comment by ibotty** [comment]
This can be closed. It somehow did not close automatically.

**Comment by ElvishJerricco** [comment]
Well the pull request isn't yet merged into master. So while a solution exists, if a new Hackage release were made tomorrow, it would not yet include the fix to this.
