### ISSUE TITLE
Metadata revisions for 4.8 and 4.8.0.1

### ISSUE THREAD

**Issue by gwils** [ekmett/free#168]
https://matrix.hackage.haskell.org/package/free#GHC-7.8/free-4.8.0.1

`free` 4.8 and 4.8.0.1 are currently failing because they can't find the module `Control.Monad.Trans.Either`. The solution is to add an upper bound to the `either` dependency.
`either` [deprecated that module](https://hackage.haskell.org/package/either-4.5/changelog) in version `4.5` and then [removed it](https://hackage.haskell.org/package/either-5/changelog) in `5`, so the correct upper bound is `either < 4.6`

**Comment by hvr** [comment]
Thanks, I've just revised them as you suggested!

**Comment by RyanGlScott** [comment]
Thanks, @hvr!
