### ISSUE TITLE
Dangling Links 

### ISSUE THREAD

**Issue by yaitskov** [ekmett/free#218]
I am trying to learn church encoded free monads, but all haddock links are broken and even googling them by subject doesn't give satisfactory results.

Page with links
https://hackage.haskell.org/package/free-5.1.9/docs/Control-Monad-Free-Church.html

Broken Links:
http://comonad.com/reader/2011/free-monads-for-less/
http://comonad.com/reader/2011/free-monads-for-less-2/

comonad.com has just stub page

**Comment by carbolymer** [comment]
Seems that Comonad.Reader is mirrored on github. Correct links:
https://ekmett.github.io/reader/2011/free-monads-for-less-1/
https://ekmett.github.io/reader/2011/free-monads-for-less-2/

**Comment by yaitskov** [comment]
https://ekmett.github.io/reader/2011/free-monads-for-less
